name: Benchmarks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  benchmark:
    name: Performance Regression Check
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libomp-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DENABLE_BENCHMARKS=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release -j$(nproc)

    - name: Run benchmarks
      run: |
        cd ${{github.workspace}}/build
        ./neural_network_benchmark --benchmark_format=json --benchmark_out=benchmark_result.json

    - name: Create gh-pages branch if not exists
      run: |
        git checkout -b gh-pages || git checkout gh-pages
        git reset --hard origin/gh-pages || true
        mkdir -p dev/bench
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        name: C++ Benchmark
        tool: 'googlecpp'
        output-file-path: build/benchmark_result.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true
        alert-threshold: '150%'
        comment-on-alert: true
        fail-on-alert: true
        gh-pages-branch: 'gh-pages'
        benchmark-data-dir-path: 'dev/bench'
