name: Benchmarks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  benchmark:
    name: Performance Regression Check
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libomp-dev

    - name: Clean build directory
      run: rm -rf build

    - name: Configure CMake
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE=Release \
          -DENABLE_BENCHMARKS=ON

    - name: Build
      working-directory: build
      run: |
        cmake --build . --config Release -j$(nproc)

    - name: Run benchmarks
      working-directory: build
      run: |
        ./neural_network_benchmark --benchmark_format=json --benchmark_out=benchmark_result.json

    - name: Configure Pages
      uses: actions/configure-pages@v4

    - name: Upload benchmark results
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'build/benchmark_result.json'

    - name: Deploy benchmark results
      id: deployment
      uses: actions/deploy-pages@v4

    - name: Store benchmark data
      uses: benchmark-action/github-action-benchmark@v1
      with:
        name: C++ Neural Network Benchmarks
        tool: 'googlecpp'
        output-file-path: build/benchmark_result.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true
        alert-threshold: '150%'
        comment-on-alert: true
