name: Benchmarks

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential libomp-dev

    - name: Clean and Configure CMake
      run: |
        rm -rf build/
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_BENCHMARKS=ON

    - name: Build
      working-directory: build
      run: |
        make clean || true
        make

    - name: Run Benchmarks
      working-directory: build
      run: |
        ./neural_network_benchmark || true

    - name: Store Benchmark Results
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: benchmark-action/github-action-benchmark@v1
      with:
        name: C++ Benchmark
        tool: 'googlecpp'
        output-file-path: build/benchmark_result.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true
        alert-threshold: '150%'
        comment-on-alert: true
        fail-on-alert: true
