name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential libomp-dev

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Run Tests
      working-directory: build
      run: ctest -C Release --output-on-failure

    - name: Create Release Package
      run: |
        cd build
        cpack -G TGZ

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: build/customneuralnetworks*.tar.gz
        generate_release_notes: true
        draft: false
        prerelease: false
