name: Security Scan

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run CodeQL Analysis
      uses: github/codeql-action/init@v2
      with:
        languages: cpp

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y flawfinder

    - name: Run Flawfinder
      run: |
        flawfinder --html --minlevel=3 ${{github.workspace}} > flawfinder-report.html

    - name: Upload Flawfinder Report
      uses: actions/upload-artifact@v3
      with:
        name: flawfinder-report
        path: flawfinder-report.html
