name: Security Scan

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: cpp

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:cpp"

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y flawfinder

    - name: Run Flawfinder
      run: |
        flawfinder --html --minlevel=3 . > flawfinder-report.html

    - name: Upload Flawfinder Report
      uses: actions/upload-pages-artifact@v3
      with:
        name: flawfinder-report
        path: flawfinder-report.html
