name: Security Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly

permissions:
  contents: read
  security-events: write

jobs:
  analyze:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install flawfinder
      run: |
        sudo apt-get update
        sudo apt-get install -y flawfinder

    - name: Create reports directory
      run: mkdir -p reports

    - name: Run flawfinder
      run: |
        # Create a list of directories to scan, excluding dot directories and build directories
        find . -type d -not -path '*/\.*' -not -path './build/*' -not -path './_deps/*' > dirs_to_scan.txt
        # Run flawfinder on the filtered directories
        cat dirs_to_scan.txt | xargs flawfinder --html --minlevel=3 > reports/flawfinder-report.html

    - name: Upload flawfinder results as artifact
      uses: actions/upload-artifact@v3
      with:
        name: flawfinder-report
        path: reports/flawfinder-report.html
        retention-days: 14

    # Add CodeQL analysis
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: cpp

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:cpp"
